export function mountDiscoveryLab(labRoot) {
const find=s=>labRoot.querySelector(s),all=s=>[...labRoot.querySelectorAll(s)];
function selectLab(name){all('[role=tab]').forEach(b=>{const on=b.dataset.lab===name;b.setAttribute('aria-selected',on);b.tabIndex=on?0:-1});all('[role=tabpanel]').forEach(p=>p.hidden=p.id!=='panel-'+name);if(name==='map')drawMap()}
all('[role=tab]').forEach((b,i,buttons)=>{b.onclick=()=>selectLab(b.dataset.lab);b.onkeydown=e=>{let n;if(e.key==='ArrowRight')n=(i+1)%3;if(e.key==='ArrowLeft')n=(i+2)%3;if(e.key==='Home')n=0;if(e.key==='End')n=2;if(n!==undefined){e.preventDefault();selectLab(buttons[n].dataset.lab);buttons[n].focus()}}});
const map=find('#decision-map'),context=map.getContext('2d');let selectedClass=0,cursor=[.5,.5],showCursor=false;
const initial=[[.14,.2,0],[.22,.35,0],[.18,.6,0],[.37,.28,0],[.38,.56,0],[.28,.8,0],[.65,.18,1],[.82,.28,1],[.73,.52,1],[.57,.7,1],[.86,.8,1],[.79,.64,1]];let samples=initial.map(p=>p.slice());
function vote(x,y,k){const nearest=samples.map(([a,b,c])=>({d:(a-x)**2+(b-y)**2,c})).sort((a,b)=>a.d-b.d).slice(0,k);return nearest.reduce((s,p)=>s+p.c,0)/nearest.length}
function drawMap(){const light=document.documentElement.dataset.theme==='day';const k=Number(find('#neighbor-count').value);find('#neighbor-value').textContent=k;context.clearRect(0,0,720,430);for(let y=0;y<430;y+=10)for(let x=0;x<720;x+=10){const v=vote((x+5)/720,(y+5)/430,k);context.fillStyle=v>.5?(light?'#ffe2cc':'#744633'):v<.5?(light?'#dce6ff':'#293e72'):(light?'#ebe1f3':'#4b4260');context.fillRect(x,y,10,10)}context.strokeStyle=light?'#32496a18':'#d8e5ff12';context.lineWidth=1;for(let x=0;x<720;x+=60){context.beginPath();context.moveTo(x,0);context.lineTo(x,430);context.stroke()}for(let y=0;y<430;y+=60){context.beginPath();context.moveTo(0,y);context.lineTo(720,y);context.stroke()}samples.forEach(([x,y,c])=>{x*=720;y*=430;context.beginPath();if(c){context.moveTo(x,y-8);context.lineTo(x+8,y);context.lineTo(x,y+8);context.lineTo(x-8,y);context.closePath()}else context.arc(x,y,7,0,Math.PI*2);context.fillStyle=c?(light?'#ad471c':'#ffad7f'):(light?'#355aba':'#aabfff');context.shadowColor=c?'#fa7956':'#829dff';context.shadowBlur=12;context.fill();context.shadowBlur=0;context.strokeStyle=light?'#fff':'#f3f6ff';context.stroke()});if(showCursor){const[x,y]=cursor;context.strokeStyle=light?'#243f79':'#fff';context.beginPath();context.moveTo(x*720-11,y*430);context.lineTo(x*720+11,y*430);context.moveTo(x*720,y*430-11);context.lineTo(x*720,y*430+11);context.stroke()}find('#map-status').textContent=samples.length+' examples · '+Math.min(k,samples.length)+' neighbors used per prediction.';find('#map-undo').disabled=samples.length<=initial.length}
function addPoint(x,y){if(samples.length>=100){find('#map-status').textContent='100-example limit reached. Undo a point or reset to keep exploring.';return}samples.push([Math.max(0,Math.min(1,x)),Math.max(0,Math.min(1,y)),selectedClass]);drawMap()}
function chooseClass(c){selectedClass=c;find('#class-blue').setAttribute('aria-pressed',c===0);find('#class-orange').setAttribute('aria-pressed',c===1)}
find('#class-blue').onclick=()=>chooseClass(0);find('#class-orange').onclick=()=>chooseClass(1);map.onclick=e=>{const r=map.getBoundingClientRect();addPoint((e.clientX-r.left)/r.width,(e.clientY-r.top)/r.height)};map.onkeydown=e=>{if(e.key.toLowerCase()==='b')chooseClass(0);if(e.key.toLowerCase()==='o')chooseClass(1);if(e.key.startsWith('Arrow')){e.preventDefault();showCursor=true;cursor[0]=Math.max(.02,Math.min(.98,cursor[0]+(e.key==='ArrowRight'?.025:e.key==='ArrowLeft'?-.025:0)));cursor[1]=Math.max(.02,Math.min(.98,cursor[1]+(e.key==='ArrowDown'?.04:e.key==='ArrowUp'?-.04:0)));drawMap()}if(e.key==='Enter'){e.preventDefault();addPoint(...cursor)}};map.onblur=()=>{showCursor=false;drawMap()};find('#neighbor-count').oninput=drawMap;find('#map-reset').onclick=()=>{samples=initial.map(p=>p.slice());drawMap()};find('#map-undo').onclick=()=>{if(samples.length>initial.length)samples.pop();drawMap()};drawMap();
const contexts={river:{words:['We','sat','by','the','river','bank'],focus:4,note:'“River” helps tell us that “bank” means the land beside water.'},money:{words:['We','put','money','in','the','bank'],focus:2,note:'“Money” helps tell us that “bank” means a financial institution.'}};let selectedWord=5;
function attention(){const light=document.documentElement.dataset.theme==='day';const c=contexts[find('#attention-example').value];let values=c.words.map((_,i)=>i===selectedWord?15:i===c.focus?50:7);if(selectedWord===c.focus)values[5]=50;let total=values.reduce((a,b)=>a+b);values=values.map(v=>v/total);const percentages=values.map(v=>Math.floor(v*100));percentages[values.indexOf(Math.max(...values))]+=100-percentages.reduce((a,b)=>a+b);find('#attention-words').innerHTML=c.words.map((word,i)=>`<button data-word="${i}" aria-pressed="${i===selectedWord}">${word}</button>`).join('');find('#attention-arcs').innerHTML=values.map((v,i)=>{if(i===selectedWord)return '';const a=50+selectedWord*100,b=50+i*100;return `<path d="M${a} 10 Q${(a+b)/2} ${45+Math.abs(a-b)*.36} ${b} 10" fill="none" stroke="${i===c.focus?(light?'#517a1f':'#d7fa78'):(light?'#4866bc':'#97adff')}" stroke-width="${1+v*12}" opacity="${.2+v}"/><circle cx="${b}" cy="10" r="${3+v*10}" fill="#a4baff"/>`}).join('');find('#attention-bars').innerHTML=c.words.map((word,i)=>`<div><span>${word}</span><div><i style="height:${values[i]*160+6}px;background:${i===c.focus?(light?'#517a1f':'#d7fa78'):(light?'#4866bc':'#92aaff')}"></i></div><b>${percentages[i]}%</b></div>`).join('');find('#attention-explanation').textContent='Selected “'+c.words[selectedWord]+'”. '+(selectedWord===5?c.note:'Explore the illustrated links, then select “bank” to compare the two meanings.');all('[data-word]').forEach(b=>b.onclick=()=>{selectedWord=Number(b.dataset.word);attention();find(`[data-word="${selectedWord}"]`)?.focus()})}
find('#attention-example').onchange=()=>{selectedWord=5;attention()};attention();
const kernels={vertical:[-1,0,1,-1,0,1,-1,0,1],horizontal:[-1,-1,-1,0,0,0,1,1,1],blur:Array(9).fill(1/9)};let pixels=Array.from({length:25},(_,i)=>{const r=Math.floor(i/5),c=i%5;return r>0&&r<4&&c>0&&c<4?1:0}),outputCell=4;
function vision(){const filter=find('#vision-filter').value,kernel=kernels[filter],row=Math.floor(outputCell/3),col=outputCell%3;let results=Array.from({length:9},(_,i)=>kernel.reduce((s,k,j)=>s+k*pixels[(Math.floor(i/3)+Math.floor(j/3))*5+i%3+j%3],0));find('#vision-input').innerHTML=pixels.map((p,i)=>{const r=Math.floor(i/5),c=i%5;return `<button data-paint="${i}" aria-label="Pixel row ${r+1}, column ${c+1}" aria-pressed="${!!p}" class="${p?'lit':''} ${r>=row&&r<row+3&&c>=col&&c<col+3?'in-patch':''}"></button>`}).join('');find('#vision-output').innerHTML=results.map((v,i)=>`<button data-output="${i}" aria-label="Output row ${Math.floor(i/3)+1}, column ${i%3+1}: ${v.toFixed(2)}" aria-pressed="${i===outputCell}" style="background:${v<0?'rgba(255,135,91,':'rgba(122,155,255,'}${.1+Math.min(1,Math.abs(v)/(filter==='blur'?1:3))*.65})">${filter==='blur'?v.toFixed(2):v}</button>`).join('');find('#kernel-matrix').innerHTML=kernel.map(v=>`<span>${filter==='blur'?'⅑':v}</span>`).join('');find('#vision-formula').textContent='Selected patch × filter weights = '+results[outputCell].toFixed(2);find('#vision-explanation').textContent=filter==='blur'?'Average the nine pixels to soften sharp changes.':'Subtract one side of the patch from the other. A larger magnitude indicates a stronger '+(filter==='vertical'?'left-to-right':'top-to-bottom')+' change.';all('[data-paint]').forEach(b=>b.onclick=()=>{const index=Number(b.dataset.paint);pixels[index]^=1;vision();find(`[data-paint="${index}"]`)?.focus()});all('[data-output]').forEach(b=>b.onclick=()=>{outputCell=Number(b.dataset.output);vision();find(`[data-output="${outputCell}"]`)?.focus()})}
find('#vision-filter').onchange=vision;find('#vision-clear').onclick=()=>{pixels=Array(25).fill(0);vision()};find('#vision-shape').onclick=()=>{pixels=Array.from({length:25},(_,i)=>{const r=Math.floor(i/5),c=i%5;return +(r>0&&r<4&&c>0&&c<4)});vision()};vision();

const onTheme = () => {drawMap();attention();vision()}; document.addEventListener('themechange',onTheme); return () => document.removeEventListener('themechange',onTheme);

}
